CREATE TABLE warehouse (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    warehouse_name TEXT,
    warehouse_address TEXT,
    zipcode INTEGER REFERENCES zipcodes(id) NOT NULL,
    UNIQUE (warehouse_name, warehouse_address, zipcode) -- to avoid duplicate entries to the table
);