CREATE TABLE zipcodes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    zipcode VARCHAR(10) NOT NULL,
    city TEXT NOT NULL,
    state_id INTEGER REFERENCES states(id) NOT NULL,
    country TEXT NOT NULL,
    UNIQUE (zipcode, city, state_id, country) -- to avoid duplicate entries to the table
);