CREATE TABLE broker (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mc_num VARHCAR(6) NOT NULL UNIQUE,
    broker_name TEXT NOT NULL,
    broker_address TEXT,
    broker_zipcode REFERENCES zipcodes(id),
    broker_dispatch_email email NOT NULL,
    broker_dispatch_phone VARCHAR(20) NOT NULL,
    borker_acct_email email,
    broker_acct_num VARCHAR(20)
);