CREATE TABLE loads(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    load_num TEXT NOT NULL,
    broker_id INTEGER REFERENCES broker(id),
    loaded_miles NUMERIC DEFAULT 0 NOT NULL,
    load_status load_status_enum DEFAULT 'booked' NOT NULL,
    invoice_num SERIAL
);