CREATE TABLE load_pricing (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    load_id INTEGER REFERENCES loads(id) NOT NULL,
    lumper NUMERIC(7,2) DEFAULT 0.00,
    detention_hrs NUMERIC(7,2) DEFAULT 0.00,
    detention_pay_per_hr NUMERIC(7,2) DEFAULT 0.00,
    layover_days NUMERIC(4,2) DEFAULT 0,
    layover_per_day NUMERIC(7,2) DEFAULT 0.00,
    rate NUMERIC(7,2) DEFAULT 0.00,
    deduction_info TEXT,
    deduction_amt NUMERIC(7,2) DEFAULT 0.00
);