CREATE TABLE driver (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    driver_first_name TEXT NOT NULL,
    driver_last_name TEXT NOT NULL,
    driver_street_address TEXT NOT NULL,
    driver_zipcode INTEGER REFERENCES zipcodes(id) NOT NULL,
    driver_salary NUMERIC(4,2) DEFAULT 0.00 NOT NULL,
    employment_start_date DATE DEFAULT NOW() NOT NULL,
    exployment_end_date DATE,
    driver_work_phone VARCHAR(20) NOT NULL,
    driver_home_phone VARCHAR(20),
    driver_ssn VARCHAR(8) NOT NULL UNIQUE
)