CREATE TABLE driver_license (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    licesne_num VARCHAR(50) NOT NULL UNIQUE,
    license_state_id INTEGER REFERENCES states(id) NOT NULL,
    license_exp DATE NOT NULL,
    driver_id INTEGER REFERENCES driver(id) NOT NULL
);